[tool.poetry]
name = "deeper"
version = "0.1.0"
description = "A collection of deep learning models"
authors = ["DDiaz"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
tqdm = "^4.49.0"
scikit-learn = "^0.23.2"
tensorflow = "^2.3.1"

[tool.poetry.dev-dependencies]
ipython = "^7.18.1"
black = "^20.8b1"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
